### ISSUE TITLE
Consider some mods (see end)

### ISSUE THREAD

**Issue by anowacki** [JuliaTime/NanoDates.jl#9]
There are many things exported from NanoDates.jl that seem somewhat curious.  For example, I don't understand why a user would need to have `CapitalT` (`'T'`) exported.  Likewise for many others.  (`SingleSpace`, etc.)  However, of course there may be very good reasons why you do export these, and please feel free to ignore my question/suggestion here.

Just from the point of view of a user, below I have listed those exports which I think could reasonably be removed in a future breaking change (e.g., v0.2):

### Characters
- `CapitalT`
- `SingleSpace`
- `SmallCapitalT`
- `SmallWhiteCircle`
- `SmallWhiteStar`
- `Underscore`

### Others
I'm not sure from the documentation if this is meant to be used as part of the API, or is really internal:
- `reset_timekeeping`

**Comment by JeffreySarnoff** [comment]
Yes .. and not breaking, more like lawn keeping.
While converging on a smaller notion of the most substantive aspects of higher resolution timekeeping to promulgate advantageously for others, I made hands full of code to clarify what most simplified, what may be more generalized, how one might show and see the information with less effort and what could become very fast running.  JuliaCon arrives just as the code is become more nicely dressed, and in advance of some real dusting, and letting some go as charitable donations.

Some of the reason for this package is to see how it may be when well revisited as others become familiar with specifics.  So, yes.

**Comment by JeffreySarnoff** [comment]
This is a "known very near term to do" and there are places with lines of code that were essential until better ways with their own, more coherent functions and compact operative approaches got got.

**Comment by JeffreySarnoff** [comment]
`reset_timekeeping` serves two overlapping purposes ..
it turns out that there is a way of looking at them wherein one subsumes (really, protects and provides for) the other.  While client access to this is no longer necessary .. particularly as it may be accessed through `import Package: packaged_onthe_inside`, there are important buildables that may lean on NanoDates for which that activity simplifies the overall effort.  I have let it remain published so more potential may roll downhill into valleys of the well provisioned.   I may replace its current access with a better writeup of why other constructs may care for it.

**Comment by anowacki** [comment]
Okay, sorry for the noise.  I'll hold off on comments and suggestions for now, since it seems you have plans for how things will develop.

**Comment by JeffreySarnoff** [comment]
just noticed this -- you have lived with the package for a while .. any changes you suggest That are surface level?

**Comment by JeffreySarnoff** [comment]
punting on this
